/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAtaRouteImport } from './routes/_authenticated/ata'
import { Route as AuthenticatedBlendRouteImport } from './routes/_authenticated/blend'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedEquipamentosRouteImport } from './routes/_authenticated/equipamentos'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedCadastrosAtalhosRouteImport } from './routes/_authenticated/cadastros/atalhos'
import { Route as AuthenticatedCadastrosBancosRouteImport } from './routes/_authenticated/cadastros/bancos'
import { Route as AuthenticatedCadastrosEquipamentosRouteImport } from './routes/_authenticated/cadastros/equipamentos'
import { Route as AuthenticatedCadastrosMensagensRouteImport } from './routes/_authenticated/cadastros/mensagens'
import { Route as AuthenticatedRelatoriosBlendRouteImport } from './routes/_authenticated/relatorios/blend'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtaRoute = AuthenticatedAtaRouteImport.update({
  id: '/ata',
  path: '/ata',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlendRoute = AuthenticatedBlendRouteImport.update({
  id: '/blend',
  path: '/blend',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosRoute =
  AuthenticatedEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosAtalhosRoute =
  AuthenticatedCadastrosAtalhosRouteImport.update({
    id: '/cadastros/atalhos',
    path: '/cadastros/atalhos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosBancosRoute =
  AuthenticatedCadastrosBancosRouteImport.update({
    id: '/cadastros/bancos',
    path: '/cadastros/bancos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosEquipamentosRoute =
  AuthenticatedCadastrosEquipamentosRouteImport.update({
    id: '/cadastros/equipamentos',
    path: '/cadastros/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosMensagensRoute =
  AuthenticatedCadastrosMensagensRouteImport.update({
    id: '/cadastros/mensagens',
    path: '/cadastros/mensagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosBlendRoute =
  AuthenticatedRelatoriosBlendRouteImport.update({
    id: '/relatorios/blend',
    path: '/relatorios/blend',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ata': typeof AuthenticatedAtaRoute
  '/blend': typeof AuthenticatedBlendRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/cadastros/atalhos': typeof AuthenticatedCadastrosAtalhosRoute
  '/cadastros/bancos': typeof AuthenticatedCadastrosBancosRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/mensagens': typeof AuthenticatedCadastrosMensagensRoute
  '/relatorios/blend': typeof AuthenticatedRelatoriosBlendRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ata': typeof AuthenticatedAtaRoute
  '/blend': typeof AuthenticatedBlendRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/': typeof AuthenticatedIndexRoute
  '/cadastros/atalhos': typeof AuthenticatedCadastrosAtalhosRoute
  '/cadastros/bancos': typeof AuthenticatedCadastrosBancosRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/mensagens': typeof AuthenticatedCadastrosMensagensRoute
  '/relatorios/blend': typeof AuthenticatedRelatoriosBlendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ata': typeof AuthenticatedAtaRoute
  '/_authenticated/blend': typeof AuthenticatedBlendRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cadastros/atalhos': typeof AuthenticatedCadastrosAtalhosRoute
  '/_authenticated/cadastros/bancos': typeof AuthenticatedCadastrosBancosRoute
  '/_authenticated/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/_authenticated/cadastros/mensagens': typeof AuthenticatedCadastrosMensagensRoute
  '/_authenticated/relatorios/blend': typeof AuthenticatedRelatoriosBlendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ata'
    | '/blend'
    | '/configuracoes'
    | '/equipamentos'
    | '/mensagens'
    | '/cadastros/atalhos'
    | '/cadastros/bancos'
    | '/cadastros/equipamentos'
    | '/cadastros/mensagens'
    | '/relatorios/blend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ata'
    | '/blend'
    | '/configuracoes'
    | '/equipamentos'
    | '/mensagens'
    | '/'
    | '/cadastros/atalhos'
    | '/cadastros/bancos'
    | '/cadastros/equipamentos'
    | '/cadastros/mensagens'
    | '/relatorios/blend'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ata'
    | '/_authenticated/blend'
    | '/_authenticated/configuracoes'
    | '/_authenticated/equipamentos'
    | '/_authenticated/mensagens'
    | '/_authenticated/'
    | '/_authenticated/cadastros/atalhos'
    | '/_authenticated/cadastros/bancos'
    | '/_authenticated/cadastros/equipamentos'
    | '/_authenticated/cadastros/mensagens'
    | '/_authenticated/relatorios/blend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ata': {
      id: '/_authenticated/ata'
      path: '/ata'
      fullPath: '/ata'
      preLoaderRoute: typeof AuthenticatedAtaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blend': {
      id: '/_authenticated/blend'
      path: '/blend'
      fullPath: '/blend'
      preLoaderRoute: typeof AuthenticatedBlendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos': {
      id: '/_authenticated/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AuthenticatedEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/atalhos': {
      id: '/_authenticated/cadastros/atalhos'
      path: '/cadastros/atalhos'
      fullPath: '/cadastros/atalhos'
      preLoaderRoute: typeof AuthenticatedCadastrosAtalhosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/bancos': {
      id: '/_authenticated/cadastros/bancos'
      path: '/cadastros/bancos'
      fullPath: '/cadastros/bancos'
      preLoaderRoute: typeof AuthenticatedCadastrosBancosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/equipamentos': {
      id: '/_authenticated/cadastros/equipamentos'
      path: '/cadastros/equipamentos'
      fullPath: '/cadastros/equipamentos'
      preLoaderRoute: typeof AuthenticatedCadastrosEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/mensagens': {
      id: '/_authenticated/cadastros/mensagens'
      path: '/cadastros/mensagens'
      fullPath: '/cadastros/mensagens'
      preLoaderRoute: typeof AuthenticatedCadastrosMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/blend': {
      id: '/_authenticated/relatorios/blend'
      path: '/relatorios/blend'
      fullPath: '/relatorios/blend'
      preLoaderRoute: typeof AuthenticatedRelatoriosBlendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtaRoute: typeof AuthenticatedAtaRoute
  AuthenticatedBlendRoute: typeof AuthenticatedBlendRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEquipamentosRoute: typeof AuthenticatedEquipamentosRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCadastrosAtalhosRoute: typeof AuthenticatedCadastrosAtalhosRoute
  AuthenticatedCadastrosBancosRoute: typeof AuthenticatedCadastrosBancosRoute
  AuthenticatedCadastrosEquipamentosRoute: typeof AuthenticatedCadastrosEquipamentosRoute
  AuthenticatedCadastrosMensagensRoute: typeof AuthenticatedCadastrosMensagensRoute
  AuthenticatedRelatoriosBlendRoute: typeof AuthenticatedRelatoriosBlendRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtaRoute: AuthenticatedAtaRoute,
  AuthenticatedBlendRoute: AuthenticatedBlendRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEquipamentosRoute: AuthenticatedEquipamentosRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCadastrosAtalhosRoute: AuthenticatedCadastrosAtalhosRoute,
  AuthenticatedCadastrosBancosRoute: AuthenticatedCadastrosBancosRoute,
  AuthenticatedCadastrosEquipamentosRoute:
    AuthenticatedCadastrosEquipamentosRoute,
  AuthenticatedCadastrosMensagensRoute: AuthenticatedCadastrosMensagensRoute,
  AuthenticatedRelatoriosBlendRoute: AuthenticatedRelatoriosBlendRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
